### ISSUE TITLE
Running commit f7f6 gives me a crash

### ISSUE THREAD

**Issue by ethereumdegen** [bevyengine/bevy_editor_prototypes#111]
thread '<unnamed>' panicked at /home/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ash-0.38.0+1.3.281/src/extensions_generated.rs:2361:29:
Unable to load cmd_begin_debug_utils_label_ext
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind

I get this when i do 'cargo run'  on 'bevy_editor'   ( i assume this is how to boot? i  dont see in the readme where it says)

**Comment by tim-blackbird** [comment]
Yes, `cargo run` is correct :)
That's an odd panic. Does the bevy main branch run for fine for you?

**Comment by MiniaczQ** [comment]
Is it fixed after `cargo update`?
